zebra-0.95-pre2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -858,6 +858,7 @@ Optional Features:
   --disable-ripngd        do not build ripngd
   --disable-ospfd         do not build ospfd
   --disable-ospf6d        do not build ospf6d
+  --enable-irdp           enable IRDP server support in zebra
   --disable-bgp-announce, turn off BGP route announcement
   --enable-netlink        force to use Linux netlink interface
   --enable-broken-aliases enable aliases as distinct interfaces for Linux 2.2.X
@@ -867,11 +868,13 @@ Optional Features:
   --enable-opaque-lsa     enable OSPF Opaque-LSA support (RFC2370)
   --enable-ospf-te        enable Traffic Engineering Extension to OSPF
   --enable-multipath=ARG  enable multipath function, ARG must be digit
+  --enable-tcp-signature  enable TCP MD5 Signature Option (RFC2385) (for Linux and OpenBSD)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-cflags           Set CFLAGS for use in compilation.
+  --with-linkbase         Set local library base for use in compilation.
   --with-libpam           use libpam for PAM support in vtysh
 
 Some influential environment variables:
@@ -1543,7 +1546,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=zebra
- VERSION=0.94
+ VERSION=0.95
 
 
 cat >>confdefs.h <<_ACEOF
@@ -1741,6 +1744,16 @@ if test "x$with_cflags" != "x" ; then
   CFLAGS="$with_cflags" ; cflags_specified=yes ;
 elif test -n "$CFLAGS" ; then
   cflags_specified=yes ;
+fi
+
+
+# Check whether --with-linkbase or --without-linkbase was given.
+if test "${with_linkbase+set}" = set; then
+  withval="$with_linkbase"
+
+fi;
+if test "x$with_linkbase" != "x" ; then
+  linkbase_specified=yes ;
 fi
 
 ac_ext=c
@@ -2758,6 +2771,10 @@ if test "x$cflags_specified" = "x" ; then
   CFLAGS="$CFLAGS -Wall"
 fi
 
+if test "x$linkbase_specified" != "x" ; then
+  CFLAGS="$CFLAGS -I${with_linkbase}/include -L${with_linkbase}/lib" ;
+fi
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -3346,6 +3363,11 @@ if test "${enable_ospf6d+set}" = set; then
   enableval="$enable_ospf6d"
 
 fi;
+# Check whether --enable-irdp or --disable-irdp was given.
+if test "${enable_irdp+set}" = set; then
+  enableval="$enable_irdp"
+
+fi;
 # Check whether --enable-bgp-announce or --disable-bgp-announce was given.
 if test "${enable_bgp_announce+set}" = set; then
   enableval="$enable_bgp_announce"
@@ -3397,7 +3419,11 @@ if test "${enable_multipath+set}" = set; then
   enableval="$enable_multipath"
 
 fi;
+# Check whether --enable-tcp-signature or --disable-tcp-signature was given.
+if test "${enable_tcp_signature+set}" = set; then
+  enableval="$enable_tcp_signature"
 
+fi;
 
 if test "${enable_broken_aliases}" = "yes"; then
   if test "${enable_netlink}" = "yes"
@@ -3429,6 +3455,14 @@ _ACEOF
 
 fi
 
+if test "${enable_irdp}" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IRDP
+_ACEOF
+
+fi
+
 if test "${enable_opaque_lsa}" = "yes"; then
 
 cat >>confdefs.h <<\_ACEOF
@@ -3449,7 +3483,6 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 fi
-
 
 
 MULTIPATH_NUM=1
@@ -4428,7 +4461,8 @@ fi
 esac
 
 case "${enable_vtysh}" in
-  "yes") VTYSH="vtysh";
+  "yes")
+    VTYSH="vtysh";
 
 cat >>confdefs.h <<\_ACEOF
 #define VTYSH
@@ -4559,6 +4593,71 @@ _ACEOF
 
   LIBS="-lncurses $LIBS"
 
+else
+
+echo "$as_me:$LINENO: checking for tputs in -ltermcap" >&5
+echo $ECHO_N "checking for tputs in -ltermcap... $ECHO_C" >&6
+if test "${ac_cv_lib_termcap_tputs+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ltermcap  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char tputs ();
+int
+main ()
+{
+tputs ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_termcap_tputs=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_termcap_tputs=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_termcap_tputs" >&5
+echo "${ECHO_T}$ac_cv_lib_termcap_tputs" >&6
+if test $ac_cv_lib_termcap_tputs = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBTERMCAP 1
+_ACEOF
+
+  LIBS="-ltermcap $LIBS"
+
+fi
+
 fi
 
 fi
@@ -4621,12 +4720,12 @@ _ACEOF
 
 fi
 
-         if test $ac_cv_lib_readline_main = no; then
-           { { echo "$as_me:$LINENO: error: vtysh needs libreadline but was not found on your system." >&5
+    if test $ac_cv_lib_readline_main = no; then
+      { { echo "$as_me:$LINENO: error: vtysh needs libreadline but was not found on your system." >&5
 echo "$as_me: error: vtysh needs libreadline but was not found on your system." >&2;}
    { (exit 1); exit 1; }; }
-         fi
-	 if test "${ac_cv_header_readline_history_h+set}" = set; then
+    fi
+    if test "${ac_cv_header_readline_history_h+set}" = set; then
   echo "$as_me:$LINENO: checking for readline/history.h" >&5
 echo $ECHO_N "checking for readline/history.h... $ECHO_C" >&6
 if test "${ac_cv_header_readline_history_h+set}" = set; then
@@ -4757,14 +4856,17 @@ echo "${ECHO_T}$ac_cv_header_readline_history_h" >&6
 fi
 
 
-	 if test $ac_cv_header_readline_history_h = no;then
-           { { echo "$as_me:$LINENO: error: readline is too old to have readline/history.h, please update to the latest readline library." >&5
+    if test $ac_cv_header_readline_history_h = no;then
+      { { echo "$as_me:$LINENO: error: readline is too old to have readline/history.h, please update to the latest readline library." >&5
 echo "$as_me: error: readline is too old to have readline/history.h, please update to the latest readline library." >&2;}
    { (exit 1); exit 1; }; }
-	 fi
-         ;;
-  "no" ) VTYSH="";;
-  *    ) ;;
+    fi
+    ;;
+  "no")
+    VTYSH=""
+    ;;
+  *)
+    ;;
 esac
 
 if test "$with_libpam" = "yes"; then
@@ -5927,6 +6029,34 @@ if test x"$RIPNGD" = x""; then
   echo "$as_me:$LINENO: result: IPv4 only" >&5
 echo "${ECHO_T}IPv4 only" >&6
 fi
+fi
+
+if test "${enable_tcp_signature}" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_TCP_SIGNATURE
+_ACEOF
+
+  case "$host" in
+    *-linux-*)
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LINUX_TCP_SIGNATURE
+_ACEOF
+
+    ;;
+    *-openbsd*)
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENBSD_TCP_SIGNATURE
+_ACEOF
+
+    ;;
+    *)
+	echo "Sorry, your OS don't support TCP signature."
+    	exit 1
+    ;;
+  esac
 fi
 
 if test "${enable_zebra}" = "no";then
@@ -7112,6 +7242,56 @@ echo "${ECHO_T}yes" >&6
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SIN6_SCOPE_ID
+_ACEOF
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+
+if test "$zebra_cv_ipv6" = yes; then
+  echo "$as_me:$LINENO: checking whether in6addr_loopback is usable" >&5
+echo $ECHO_N "checking whether in6addr_loopback is usable... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+#include <netinet/in.h>
+
+int
+main ()
+{
+static struct in6_addr ac_i; ac_i = in6addr_loopback;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_IN6ADDR_GLOBAL
 _ACEOF
 
 else
